"""
Medical Disclaimer Module

Provides standardized medical disclaimers for AI-generated content.
All medical information extracted or generated by this system should
include appropriate disclaimers to ensure users understand the limitations.
"""

from typing import Dict, Any, Optional

# Standard medical disclaimer used throughout the application
MEDICAL_DISCLAIMER = (
    "⚠️ **Medical Disclaimer**: This information is extracted by AI and may contain errors. "
    "Always consult a qualified healthcare professional for medical advice. "
    "This service is for informational purposes only and should not be used for diagnosis, "
    "treatment, or as a substitute for professional medical judgment."
)

# Extended disclaimer for prescription information
PRESCRIPTION_DISCLAIMER = (
    "⚠️ **Important Prescription Notice**: "
    "This prescription data is automatically extracted from images using AI/OCR technology. "
    "The extraction may contain errors, omissions, or misinterpretations. "
    "\n\n"
    "• Always verify the information with the original prescription\n"
    "• Consult your doctor or pharmacist before taking any medication\n"
    "• Do not rely solely on this digital extraction for medical decisions\n"
    "• Report any discrepancies to your healthcare provider immediately"
)

# Disclaimer for medicine information queries
MEDICINE_INFO_DISCLAIMER = (
    "⚠️ **Medicine Information Disclaimer**: "
    "The information provided about medications is for educational purposes only. "
    "It is automatically generated and may not be complete or accurate. "
    "\n\n"
    "• Always read the official medication guide/packaging\n"
    "• Consult your healthcare provider for personalized advice\n"
    "• Do not start, stop, or change medication without medical supervision\n"
    "• Report any side effects to your doctor immediately"
)

# Disclaimer for symptom or condition searches
SYMPTOM_SEARCH_DISCLAIMER = (
    "⚠️ **Symptom Search Disclaimer**: "
    "Search results matching symptoms are suggestive and not diagnostic. "
    "AI matching is based on text similarity and should not replace medical evaluation. "
    "\n\n"
    "• Similar symptoms can indicate different conditions\n"
    "• Always consult a healthcare professional for diagnosis\n"
    "• Seek immediate medical attention for serious symptoms\n"
    "• Do not self-diagnose based on search results"
)

# Disclaimer for chat interactions
CHAT_DISCLAIMER = (
    "⚠️ **AI Chat Disclaimer**: "
    "This AI assistant provides general information and cannot provide medical advice, "
    "diagnosis, or treatment recommendations. "
    "\n\n"
    "• Responses are generated by AI and may contain inaccuracies\n"
    "• Always consult qualified healthcare professionals for medical concerns\n"
    "• In case of emergency, contact emergency services immediately\n"
    "• Do not share sensitive personal health information unnecessarily"
)


class DisclaimerManager:
    """
    Manager for medical disclaimers.
    Provides context-aware disclaimers for different types of content.
    """
    
    DISCLAIMER_TYPES = {
        "standard": MEDICAL_DISCLAIMER,
        "prescription": PRESCRIPTION_DISCLAIMER,
        "medicine_info": MEDICINE_INFO_DISCLAIMER,
        "symptom_search": SYMPTOM_SEARCH_DISCLAIMER,
        "chat": CHAT_DISCLAIMER,
    }
    
    @classmethod
    def get_disclaimer(cls, disclaimer_type: str = "standard") -> str:
        """
        Get a disclaimer by type.
        
        Args:
            disclaimer_type: Type of disclaimer (standard, prescription, medicine_info, etc.)
        
        Returns:
            The disclaimer text, or standard disclaimer if type not found
        """
        return cls.DISCLAIMER_TYPES.get(disclaimer_type, MEDICAL_DISCLAIMER)
    
    @classmethod
    def format_with_disclaimer(
        cls,
        content: str,
        disclaimer_type: str = "standard",
        prefix: bool = False
    ) -> str:
        """
        Format content with an appropriate disclaimer.
        
        Args:
            content: The main content to display
            disclaimer_type: Type of disclaimer to append
            prefix: If True, put disclaimer before content; if False, append after
        
        Returns:
            Formatted string with disclaimer
        """
        disclaimer = cls.get_disclaimer(disclaimer_type)
        
        separator = "\n\n---\n\n"
        
        if prefix:
            return f"{disclaimer}{separator}{content}"
        else:
            return f"{content}{separator}{disclaimer}"
    
    @classmethod
    def get_all_disclaimers(cls) -> Dict[str, str]:
        """
        Get all available disclaimers.
        
        Returns:
            Dictionary mapping disclaimer types to their text
        """
        return cls.DISCLAIMER_TYPES.copy()
    
    @classmethod
    def validate_content_has_disclaimer(
        cls,
        content: str,
        disclaimer_type: Optional[str] = None
    ) -> bool:
        """
        Check if content already contains a disclaimer.
        
        Args:
            content: The content to check
            disclaimer_type: Optional specific disclaimer type to check for
        
        Returns:
            True if a disclaimer is detected in the content
        """
        if disclaimer_type:
            disclaimer = cls.get_disclaimer(disclaimer_type)
            # Check for key phrases from the specific disclaimer
            key_phrases = ["Medical Disclaimer", "extracted by AI", "consult a qualified"]
            return all(phrase in content for phrase in key_phrases)
        
        # Check for any disclaimer indicators
        disclaimer_indicators = [
            "Medical Disclaimer",
            "⚠️",
            "**Disclaimer**",
            "consult a healthcare professional",
            "informational purposes only",
        ]
        
        return any(indicator in content for indicator in disclaimer_indicators)


# Convenience function for quick disclaimer access
def get_medical_disclaimer(disclaimer_type: str = "standard") -> str:
    """
    Get a medical disclaimer by type.
    
    Args:
        disclaimer_type: Type of disclaimer needed
    
    Returns:
        Disclaimer text
    """
    return DisclaimerManager.get_disclaimer(disclaimer_type)


def add_disclaimer_to_response(
    response_text: str,
    disclaimer_type: str = "standard"
) -> str:
    """
    Add an appropriate disclaimer to a response.
    
    Args:
        response_text: The main response content
        disclaimer_type: Type of disclaimer to add
    
    Returns:
        Response with disclaimer appended
    """
    # Check if disclaimer already present
    if DisclaimerManager.validate_content_has_disclaimer(response_text):
        return response_text
    
    return DisclaimerManager.format_with_disclaimer(
        response_text,
        disclaimer_type,
        prefix=False
    )